---
abstract: 'Send SMS messages via the CS Networks HTTP API'
author:
  - 'CS Networks <support@cs-networks.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SMS-CSNetworks
requires:
  Carp: 0
  Data::Dumper: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
version: 0.07
